In [32]:
import pandas as pd
import numpy as np

from pathlib import Path

ROOT_PATH = Path(Path.cwd()).resolve().parent
DATA_PATH = ROOT_PATH/'data'/'processed'
PROCESSED_PATH = ROOT_PATH/'data'/'processed'

In [33]:
# df = pd.DataFrame(columns=[
#     'Equipo',
#     'Dorsal',
#     'Nombre',
#     'Apellido',
#     'Posición',
#     'Altura',
#     'Fecha_Nacim',
#     'Pais_Nacim',
#     'Comunidad',
#     'Nacionalidad',
#     'Licencia'
# ])

In [34]:
df = pd.read_csv(
    DATA_PATH/'Jugadores.csv',
    dtype={
        "Equipo": "object",
        "Dorsal": "object",
        "Nombre": "object",
        "Apellido": "object",
        "Posición": "object",
        "Altura": "object",
        "Fecha_Nacim": "object",
        "Pais_Nacim": "object",
        "Comunidad": "object",
        "Nacionalidad": "object",
        "Licencia": "object"
    })

In [35]:
df.tail(10)

,Equipo,Dorsal,Nombre,Apellido,Posición,Altura,Fecha_Nacim,Pais_Nacim,Comunidad,Nacionalidad,Licencia,Foto,Bandera_Pais,Bandera_Comunidad
0,JOV,0,Henri,Drell,4,206,25/04/2000,EST,NaN,EST,EUR,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,NaN
1,JOV,1,Yannick,Kraag,3,202,16/10/2002,NLD,NaN,NLD,JFL,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,NaN
2,JOV,9,Ricky,Rubio,1,189,21/10/1990,ESP,CAT,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...

In [36]:
jugadores = []

while True:

    equipo = 'JOV'
    # equipo = input('Equipo: ').upper()
    dorsal = input('Dorsal: ')
    nombre = input('Nombre (sin apellido): ').title()
    apellido = input('Apellido: ').title()
    posicion = input('Posición: ')
    altura = input('Altura en cm: ')

    dia_nacim = input('Día de nacimiento (DD): ')
    mes_nacim = input('Mes de nacimiento (MM): ')
    año_nacim = input('Año de nacimiento (AAAA): ')
    fecha_nacim = dia_nacim + '/' + mes_nacim + '/' + año_nacim
    
    pais_nacim = input('País de Nacimiento: ').upper()

    if pais_nacim in ['ESP', 'ESPAÑA']:
        comunidad = input('Comunidad Autónoma: ').upper()
    else:
        comunidad = ''

    nacionalidad = input('Nacionalidad: ').upper()
    licencia = input('Licencia: ').upper()

    nueva_fila = {
        'Equipo': equipo,
        'Dorsal': dorsal,
        'Nombre': nombre,
        'Apellido': apellido,
        'Posición': posicion,
        'Altura': altura,
        'Fecha_Nacim': fecha_nacim,
        'Pais_Nacim': pais_nacim,
        'Comunidad': comunidad,
        'Nacionalidad': nacionalidad,
        'Licencia': licencia
    }

    jugadores.append(nueva_fila)

    continuar = input('Añadir otro jugador? (S/N): ').upper()
    if continuar != 'S':
        break

df = pd.concat(
    [df, pd.DataFrame(jugadores)],
    ignore_index=True
)

In [46]:
iso_paises = {
    'ESPAÑA': 'ESP',
    'ARGENTINA': 'ARG',
    'ITALIA': 'ITA',
    'CHEQUIA': 'CZE',
    'SENEGAL': 'SEN',
    'FRANCIA': 'FRA',
    'GEORGIA': 'GEO',
    'MALI': 'MLI',
    'ESTONIA': 'EST',
    'PAISES BAJOS': 'NLD',
    'SERBIA': 'SRB',
    'CROACIA': 'HRV',
    'HUNGRIA': 'HUN',
    'MONTENEGRO': 'MNE',
    'REINO UNIDO': 'GBR',
    'LITUANIA': 'LTU',
    'SUECIA': 'SWE'
}
df.replace(iso_paises, inplace=True)

In [47]:
df['Foto'] = 'https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/' + df['Equipo'] + '/cuerpo/' + df['Dorsal'] + '.webp?raw=true'
df['Bandera_Pais'] = 'https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/' + df['Pais_Nacim'] + '.png?raw=true'
df['Bandera_Comunidad'] = np.where(df['Comunidad'] == '', '', 'https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP/' + df['Comunidad'] + '.png?raw=true')

In [48]:
df['Pais_Nacim'].unique()

array(['EST', 'NLD', 'ESP', 'USA', 'SWE', 'CAN', 'FRA', 'HRV', 'HUN'],
      dtype=object)

In [49]:
df.tail(10)

,Equipo,Dorsal,Nombre,Apellido,Posición,Altura,Fecha_Nacim,Pais_Nacim,Comunidad,Nacionalidad,Licencia,Foto,Bandera_Pais,Bandera_Comunidad
8,JOV,22,Humberto,Ruiz,2,198,07/02/2009,ESP,CAT,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...
9,JOV,23,Michael,Ruzic,4,206,04/10/2006,FRA,,HRV,EUR,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,
10,JOV,24,Cameron,Hunt,2,191,25/08/1997,USA,,USA,EXT,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,
11,JOV,25,Yannis,Morin,5,208,31/08/1993,FRA,,FRA,EUR,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,
12,JOV,32,Ferran,Mauri,1,191,30/09/2007,ESP,CAT,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...
13,JOV,34,Diego,Niebla,2,202,18/01/2008,ESP,GAL,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...
14,JOV,35,Simon,Birgander,5,209,23/10/1997,SWE,,SWE,EUR,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,
15,JOV,44,Ante,Tomic,5,217,17/02/1987,HRV,,HRV,EUR,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,
16,JOV,88,Adam,Hanga,3,201,12/04/1989,HUN,,HUN,EUR,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,
17,JOV,17,Sam,Dekker,4,206,06/05/1994,USA,,USA,EXT,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,

In [50]:
df.to_csv(
    PROCESSED_PATH/'Jugadores.csv',
    index=False
)

In [41]:
# df.loc[26, 'Pais_Nacim'] = 'FRANCIA'

In [42]:
# df = df.drop(11)